#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

# .env is root-owned and validated again by deploy-release.sh before activation.
# shellcheck disable=SC1091
. ./.env
: "${DEPLOY_STATE_ROOT:?DEPLOY_STATE_ROOT is required}"
STATE_DIR="${DEPLOY_STATE_ROOT}/leaperone-www-cn"
CURRENT_FILE="$STATE_DIR/current.env"
HISTORY_DIR="$STATE_DIR/history"
TARGET="${1:-previous}"

[ -s "$CURRENT_FILE" ] || {
  echo "ERROR: no current CN deployment state exists" >&2
  exit 1
}

if [ "$TARGET" = previous ]; then
  CURRENT_SHA="$(sed -n 's/^WWW_CN_SOURCE_SHA=//p' "$CURRENT_FILE")"
  TARGET_FILE=
  while IFS= read -r candidate; do
    candidate_sha="$(sed -n 's/^WWW_CN_SOURCE_SHA=//p' "$candidate")"
    if [ -n "$candidate_sha" ] && [ "$candidate_sha" != "$CURRENT_SHA" ]; then
      TARGET_FILE="$candidate"
      break
    fi
  done < <(find "$HISTORY_DIR" -maxdepth 1 -type f -name '*.env' -print | sort -r)
  [ -n "$TARGET_FILE" ] || {
    echo "ERROR: no previous CN release exists" >&2
    exit 1
  }
else
  [[ "$TARGET" =~ ^[0-9a-f]{40}$ ]] || {
    echo "ERROR: rollback target must be 'previous' or a full lowercase source SHA" >&2
    exit 1
  }
  TARGET_FILE="$(find "$HISTORY_DIR" -maxdepth 1 -type f -name "*-${TARGET}.env" -print | sort -r | head -n 1)"
  [ -n "$TARGET_FILE" ] || {
    echo "ERROR: no recorded CN release exists for $TARGET" >&2
    exit 1
  }
fi

# History manifests are root-owned files generated by deploy-release.sh.
# shellcheck disable=SC1090
. "$TARGET_FILE"
export WWW_CN_SOURCE_SHA WWW_CN_IMAGE_TAG WWW_CN_IMAGE_DIGEST IMAGE_REF RELEASES_SHA
export ROLLBACK_REASON=manual-rollback
exec ./deploy-release.sh
