upstream nimei_web_active {
    server 127.0.0.1:9811;
    keepalive 32;
}

server {
    listen 80;
    server_name nimei.app www.nimei.app;
    return 301 https://nimei.app$request_uri;
}

server {
    listen 443 ssl http2;
    server_name www.nimei.app;

    ssl_certificate     /etc/nginx/ssl/nimei.app/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/nimei.app/nimei.app.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    return 301 https://nimei.app$request_uri;
}

server {
    listen 443 ssl http2;
    server_name nimei.app;

    ssl_certificate     /etc/nginx/ssl/nimei.app/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/nimei.app/nimei.app.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    include /etc/nginx/snippets/cloudflare-real-ip.conf;
    proxy_buffering off;

    location / {
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect off;
        proxy_pass http://nimei_web_active;
        client_max_body_size 20m;
    }
}
