services:
  dokilove:
    image: registry-vpc.cn-hongkong.aliyuncs.com/leaperone/dokilove:latest
    restart: always
    ports:
      - "9800:3000"
    env_file:
      - dokilove.env
    environment:
      NEXT_PUBLIC_SENTRY_DSN: https://ad95f8e28d800b13f55fa2e67e302cb9@sentry.leaper.one/7
      NEXT_PUBLIC_SENTRY_ENVIRONMENT: production
      SENTRY_DSN: https://ad95f8e28d800b13f55fa2e67e302cb9@sentry.leaper.one/7
      SENTRY_ENVIRONMENT: production
